---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-vpp-config
  namespace: calico-vpp-dataplane
data:
  vpp_dataplane_interface: eno2

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-vpp-node
  namespace: calico-vpp-dataplane
spec:
  template:
    spec:
      containers:
        - name: agent
          image: artgl/calico-agent:5ff9517
        - name: vpp
          image: artgl/calico-vpp:5ff9517
